cli4:
	python3 clidates4.py

serv4: 
	python3 servdates4.py

git_config:
	git config --global user.email oriannaalejandra.milonesalas@usp.ceu.es
	git config --global user.name orianna
	git config --global credential.helper cache 10800
