ejecutar:
	python3 cliserv2.py

git_config:
	git config --global user.email oriannaalejandra.milonesalas@usp.ceu.es
	git config --global user.name orianna
	git config --global credential.helper cache 10800
