cli3:
	python3 cli3.py

serv3: 
	python3 serv3.py

git_config:
	git config --global user.email oriannaalejandra.milonesalas@usp.ceu.es
	git config --global user.name orianna
	git config --global credential.helper cache 10800
