ejec:
	python3 clientserv2.py

diagnostico: 
	python3 clienteServidorDiagnostico.py

git:
	git config --global user.email "paloma.perezmadridlaguna@usp.ceu.es"
	git config --global user.name "Paloma PML"
	git config --global credential.helper cache
	git config --global credential.helper 'cache --timeout=18000'

