cli5:
	python3 cli5.py

serv5: 
	python3 serv5.py

git_config:
	git config --global user.email oriannaalejandra.milonesalas@usp.ceu.es
	git config --global user.name orianna
	git config --global credential.helper cache 10800
